import Head from 'next/head'
import Auth from '../components/Auth.js'

const About = () => {
    return (
        <div>
            <Head>
                <title>Crypto internship</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/token.png" />
            </Head>
            <p>This is the about page in my crypto-internship project.</p>
        </div>
    )
}

export default Auth(About)