import Head from 'next/head'

const sendOrSign = () => {
    return (
        <div>
            <Head>
                <title>Crypto internship</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/token.png" />
            </Head>
            <p>This is where you send or sign transactions.</p>
        </div>
    )
}

export default sendOrSign


